//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class recetario_RendonMesaEntities : DbContext
    {
        public recetario_RendonMesaEntities()
            : base("name=recetario_RendonMesaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_carta_restaurante> tbl_carta_restaurante { get; set; }
        public virtual DbSet<tbl_inf_original> tbl_inf_original { get; set; }
        public virtual DbSet<tbl_ing_principal> tbl_ing_principal { get; set; }
        public virtual DbSet<tbl_list_ingredientes> tbl_list_ingredientes { get; set; }
        public virtual DbSet<tbl_pasos> tbl_pasos { get; set; }
        public virtual DbSet<tbl_plato_carnes> tbl_plato_carnes { get; set; }
        public virtual DbSet<tbl_plato_postre> tbl_plato_postre { get; set; }
        public virtual DbSet<tbl_plato_vegetales> tbl_plato_vegetales { get; set; }
        public virtual DbSet<tbl_reseta> tbl_reseta { get; set; }
        public virtual DbSet<tbl_tip_plato> tbl_tip_plato { get; set; }
    }
}
