//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_plato_postre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_plato_postre()
        {
            this.tbl_carta_restaurante = new HashSet<tbl_carta_restaurante>();
        }
    
        public int idp { get; set; }
        public Nullable<int> idresetap { get; set; }
        public string nomplatop { get; set; }
        public Nullable<double> precioup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_carta_restaurante> tbl_carta_restaurante { get; set; }
        public virtual tbl_reseta tbl_reseta { get; set; }
    }
}
