//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reseta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_reseta()
        {
            this.tbl_inf_original = new HashSet<tbl_inf_original>();
            this.tbl_plato_carnes = new HashSet<tbl_plato_carnes>();
            this.tbl_plato_postre = new HashSet<tbl_plato_postre>();
            this.tbl_plato_vegetales = new HashSet<tbl_plato_vegetales>();
        }
    
        public int idreseta { get; set; }
        public Nullable<int> tpp { get; set; }
        public string nomplato { get; set; }
        public Nullable<int> idpasos { get; set; }
        public Nullable<System.TimeSpan> timtotal { get; set; }
        public string calorias { get; set; }
        public Nullable<int> listing { get; set; }
        public Nullable<int> ingpp { get; set; }
        public string utencilios { get; set; }
        public string comentario_descrip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_inf_original> tbl_inf_original { get; set; }
        public virtual tbl_ing_principal tbl_ing_principal { get; set; }
        public virtual tbl_list_ingredientes tbl_list_ingredientes { get; set; }
        public virtual tbl_pasos tbl_pasos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_plato_carnes> tbl_plato_carnes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_plato_postre> tbl_plato_postre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_plato_vegetales> tbl_plato_vegetales { get; set; }
        public virtual tbl_tip_plato tbl_tip_plato { get; set; }
    }
}
