//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_carta_restaurante
    {
        public int menu { get; set; }
        public Nullable<int> p1base { get; set; }
        public Nullable<int> p2principal { get; set; }
        public Nullable<int> postre { get; set; }
        public Nullable<double> preciott { get; set; }
        public string comentarioteveto { get; set; }
    
        public virtual tbl_plato_vegetales tbl_plato_vegetales { get; set; }
        public virtual tbl_plato_carnes tbl_plato_carnes { get; set; }
        public virtual tbl_plato_postre tbl_plato_postre { get; set; }
    }
}
